// Add List
POST http://localhost:9267/api/list/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjRiOTA2Mi0zYmQ4LTRlMTYtOWM4Ni0xNDdhYjk1ZTBkY2UiLCJ1bmlxdWVfbmFtZSI6ImIyNGI5MDYyLTNiZDgtNGUxNi05Yzg2LTE0N2FiOTVlMGRjZSIsImp0aSI6Ijg3MTU3Nzk0LTRlMjgtNDQwYS1iMmI4LWZjNzc3OThhYjY0ZCIsImlhdCI6IjIyLjAyLjIwMjAgMTQ6NTk6NTgiLCJuYmYiOjE1ODIzODM1OTgsImV4cCI6MTU4MjM4NTM5OCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.5M4y542Qi5R6u76it28JgqU98VrZRuZy6uR3u_hOVPk

{
    "title":"some list",
    "color":"#FF0000"
};
###

// Get lists
GET http://localhost:9267/api/list/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMjRiOTA2Mi0zYmQ4LTRlMTYtOWM4Ni0xNDdhYjk1ZTBkY2UiLCJ1bmlxdWVfbmFtZSI6ImIyNGI5MDYyLTNiZDgtNGUxNi05Yzg2LTE0N2FiOTVlMGRjZSIsImp0aSI6Ijg3MTU3Nzk0LTRlMjgtNDQwYS1iMmI4LWZjNzc3OThhYjY0ZCIsImlhdCI6IjIyLjAyLjIwMjAgMTQ6NTk6NTgiLCJuYmYiOjE1ODIzODM1OTgsImV4cCI6MTU4MjM4NTM5OCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.5M4y542Qi5R6u76it28JgqU98VrZRuZy6uR3u_hOVPk
